[package]
name = "intermodal"
version = "0.0.1"
authors = ["Abhijit Gadgil <gabhijit@iitbombay.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

clap = "*"
tokio = { version = "1", features = ["macros", "rt"] }
hyper = { version = "0.14.2", features = ["client", "http1"] }
hyper-tls = { version = "0.5" }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "*"
regex = "1"
lazy_static = "1.1"
env_logger = "0.8"
log = "0.4"
async-trait = "0.1"

