[package]
name = "intermodal"
version = "0.0.2"
authors = ["Abhijit Gadgil <gabhijit@iitbombay.org>"]
edition = "2018"
readme = "REDME.md"
description = "Container handling in Rust."
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

hex = "0.4"
sha2 = "0.9"
clap = "*"
bytes = { version = "1"}
futures = { version = "0.3"}
futures-util = { version = "0.3"}
tokio = { version = "1", features = ["macros", "rt"] }
hyper = { version = "0.14.2", features = ["client", "http1", "stream"] }
hyper-tls = { version = "0.5" }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "*"
regex = "1"
lazy_static = "1.1"
env_logger = "0.8"
log = "0.4"
async-trait = "0.1"
directories = "3.0"

[dev-dependencies]
wiremock = "*"
